global using NetCorePal.Extensions.AspNetCore;
global using NetCorePal.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection;
global using Ncp.CleanDDD.Infrastructure;
global using FluentValidation;
global using NetCorePal.Extensions.Primitives;
global using MediatR;
global using NetCorePal.Extensions.Domain;
global using NetCorePal.Extensions.Dto;